### ISSUE TITLE
Gerbers available for PCB?

### ISSUE THREAD

**Issue by chunkysteveo** [uvwxy/hue-cube#1]
Great project Paul, been watching this grow in Insta (as you know!) 

Going to look at some KiCad -> Eagle scripts to see if I can open the KiCad files, but are you able to upload a set of Gerber files for PCB manufacture if we don't want to use "aisler", to use OSHpark etc?

P.S. This is not an issue, but a question!! ha

Cheers,

Steve

**Comment by uvwxy** [comment]
You can open the KiCad project, open the pcbnew view and export as gerber. I have a repi that shows you how to do this

**Comment by chunkysteveo** [comment]
Thanks Paul. Time to install KiCad!

Steve
